### ISSUE TITLE
Now a Heroku app

### ISSUE THREAD

**Issue by stephenhowells** [Atrox/haikunatorphp#2]
I tossed up a little free Heroku app based on this package:

[https://haiku.herokuapp.com/](https://haiku.herokuapp.com/)

And there is an API version:

[https://haiku.herokuapp.com/api](https://haiku.herokuapp.com/api)

`$ curl https://haiku.herokuapp.com/api`

**Comment by stephenhowells** [comment]
Now the api is a json response instead of just a string, next up I'll add a route parameter to the api call for however many haikus are needed. This is more fun than it should be. :)

**Comment by stephenhowells** [comment]
Okay, landing page is fancier now. Route parameters done. For instance, this returns 15 results:
`$ curl http://haiku.herokuapp.com/api/15`

**Comment by Atrox** [comment]
Nice Idea!

Use 
`//fonts.googleapis.com/css?family=Lora:400,400italic`
instead of
`http://fonts.googleapis.com/css?family=Lora:400,400italic`
so that the font gets loaded correctly on https too.

**Comment by stephenhowells** [comment]
Good catch! The fix is now live.
