### ISSUE TITLE
Typo: "Shinny"

### ISSUE THREAD

**Issue by davesidious** [Atrox/haikunatorphp#5]
"Shinny" would be a verb, not an adjective.  Do you mean "shiny" instead?

**Comment by Atrox** [comment]
Interesting... I don't know how this got in there. I originally just copied them from a gist and I'm pretty sure "shinny" was not in there.

It is in all my other implementations as well...

**Comment by davesidious** [comment]
Not a problem - I just thought I'd mention it :)
