### ISSUE TITLE
Zendframework dependencies are abandoned

### ISSUE THREAD

**Issue by FrontEndCoffee** [Atrox/haikunatorphp#6]
The dependencies listed below have been abandoned by their maintainers. 
I would suggest an implementation, with the same specification, only using symfony/console for the command.

If you want I can draft up a PR with an implementation.

Another option would be to drop the CLI component all together, which I'd also be happy to make a PR for.

```
{
    "zfcampus/zf-console": "^1.2",
    "zendframework/zend-filter": "^2.7",
    "zendframework/zend-validator": "^2.7"
}
```

**Comment by Atrox** [comment]
Hey @FrontEndCoffee,

thank you for informing me about the abandoned packages.
I think it makes sense to remove the CLI part all together. I would be very happy to accept a PR for that.
